parameters:
    fiftyonedegrees.class: FuentesWorks\FiftyOneDegreesBundle\Service\FiftyOneDegreesWrapper

services:
    fiftyonedegrees:
        class:     %fiftyonedegrees.class%
        arguments: [%data_file_path%]